export const PENALITES = [
  // Mineures //
  {
    libelle: "ACCROCHER / HOOKING",
    code: 1,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "ASSAUT / CHARGE",
    code: 2,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "BATON ELEVE / HIGH STICKING",
    code: 3,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "CINGLER / SLASHING",
    code: 4,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "DONNER DU COUDE / ELBOWING",
    code: 5,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "DOUBLE ECHEC / CROSS CHECKING",
    code: 6,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "FAIRE TREBUCHER / TRIPPING",
    code: 7,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "MISE EN ECHEC / BODY CONTACT",
    code: 8,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "OBSTRUCTION / INTERFERENCE",
    code: 9,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "PLAQUAGE CONTRE LA BANDE / BOARDING",
    code: 10,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "RETARDER LA PARTIE / DELAY OF GAME",
    code: 11,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "RETENUE / HOLDING",
    code: 12,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  {
    libelle: "SUBSTITUTION ILLEGALE / ILLEGAL SUBSTITUTION",
    code: 13,
    dureeParDefaut: 2,
    categorie: "Mineure",
    annulableParBut: true,
  },
  // Majeures //
  {
    libelle: "CONDUITE NON SPORTIVE / UNSPORTSMANLIKE CONDUCT",
    code: 14,
    dureeParDefaut: 2,
    categorie: "Majeure",
    annulableParBut: false,
  },
  {
    libelle: "PENALITE MAJEURE / MAJOR PENALTY",
    code: 15,
    dureeParDefaut: 4,
    categorie: "Majeure",
    annulableParBut: false,
  },
  {
    libelle: "MAUVAISE CONDUITE / MISCONDUCT",
    code: 16,
    dureeParDefaut: 2,
    categorie: "Majeure",
    annulableParBut: false,
  },
  {
    libelle: "PENALITE DE MATCH / MATCH PENALTY",
    code: 17,
    dureeParDefaut: 4,
    categorie: "Majeure",
    annulableParBut: false,
  },
  {
    libelle: "LANCER DE PUNITION / PENALTY SHOT",
    code: 18,
    dureeParDefaut: 0,
    categorie: "Spéciale",
    annulableParBut: false,
  },
  {
    libelle: "RUDESSE / ROUGH PLAY",
    code: 19,
    dureeParDefaut: 4,
    categorie: "Majeure",
    annulableParBut: false,
  },
  {
    libelle: "ATHLETE EXPULSE POUR AVOIR ACCUMULE 10 MINUTES DE PENALITE",
    code: 20,
    dureeParDefaut: 0,
    categorie: "Expulsion",
    annulableParBut: false,
  },
];